// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1cdG_XdJzftKq9UBPQCCXD9h59fI_bpA',
    appId: '1:60640260678:web:d04ecb66ea1ed84ac09047',
    messagingSenderId: '60640260678',
    projectId: 'digital-3-4b092',
    authDomain: 'digital-3-4b092.firebaseapp.com',
    storageBucket: 'digital-3-4b092.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-CpY0GZdQC3B-SZpAvHCOExqkdk31BlU',
    appId: '1:60640260678:android:3b95e6d35f5896c4c09047',
    messagingSenderId: '60640260678',
    projectId: 'digital-3-4b092',
    storageBucket: 'digital-3-4b092.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoyI_8f2MCjY2dkveYJ8KiDEEjbYCacAY',
    appId: '1:60640260678:ios:8c0d6cb3cef381abc09047',
    messagingSenderId: '60640260678',
    projectId: 'digital-3-4b092',
    storageBucket: 'digital-3-4b092.appspot.com',
    iosClientId: '60640260678-1vsu2ld9n9cibh0creoou8fj0eac09ql.apps.googleusercontent.com',
    iosBundleId: 'com.example.digital3',
  );
}
